version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - darwinai
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_HOST_AUTH_METHOD=md5

  # Redis for Chatwoot (without password)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - darwinai

  # Database Preparation (runs once)
  chatwoot_db_prepare:
    image: ghcr.io/leomeirae/chatwoot:v4.1.0-custom
    command: ["bundle", "exec", "rails", "db:chatwoot_prepare"]
    depends_on:
      - postgres
      - redis
    networks:
      - darwinai
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DATABASE=chatwoot_production
      - SECRET_KEY_BASE=a9eb2be1fb5c2d015ff2f4e76f594dff42c3a68b9f8d2e1c7a5b3f9d8e2c1a4b6f7e8d9c2a1b5f6e3d7c8a9b4f2e1d6c5a8b7f3e9d2c1a6b5f8e4d7c3a9
      - REDIS_URL=redis://redis:6379/0
    restart: "no"

  # Chatwoot Rails Application
  chatwoot_rails:
    image: ghcr.io/leomeirae/chatwoot:v4.1.0-custom
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    depends_on:
      - postgres
      - redis
      - chatwoot_db_prepare
    volumes:
      - storage_data:/app/storage
      - public_data:/app/public
    networks:
      - darwinai
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - DEFAULT_LOCALE=pt_BR
      - FRONTEND_URL=https://chatwoot.darwinai.com.br
      - INTERNAL_HOST_URL=http://chatwoot_rails:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DATABASE=chatwoot_production
      - SECRET_KEY_BASE=a9eb2be1fb5c2d015ff2f4e76f594dff42c3a68b9f8d2e1c7a5b3f9d8e2c1a4b6f7e8d9c2a1b5f6e3d7c8a9b4f2e1d6c5a8b7f3e9d2c1a6b5f8e4d7c3a9
      - REDIS_URL=redis://redis:6379/0
      # SMTP Config
      - MAILER_SENDER_EMAIL=leonardo@darwinai.com.br
      - SMTP_DOMAIN=darwinai.com.br
      - SMTP_ADDRESS=smtp.hostinger.com
      - SMTP_PORT=587
      - SMTP_SSL=false
      - SMTP_USERNAME=leonardo@darwinai.com.br
      - SMTP_PASSWORD=@Atjlc151523
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=none
      # Other Config
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - USE_INBOX_AVATAR_FOR_BOT=true
      - FORCE_SSL=false
      - TZ=America/Sao_Paulo
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local
  public_data:
    driver: local

networks:
  darwinai:
    external: true 