version: '3.8'

services:
  baileys-api:
    image: ghcr.io/fazer-ai/baileys-api:latest
    container_name: baileys-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3025
      - LOG_LEVEL=info
      - BAILEYS_LOG_LEVEL=warn
      - BAILEYS_PRINT_QR=false
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WEBHOOK_RETRY_POLICY_MAX_RETRIES=3
      - WEBHOOK_RETRY_POLICY_RETRY_INTERVAL=5000
      - WEBHOOK_RETRY_POLICY_BACKOFF_FACTOR=3
      - CORS_ORIGIN=${CHATWOOT_URL}
      - BAILEYS_API_KEY=${BAILEYS_API_KEY}
      - WEBHOOK_URL=${CHATWOOT_URL}/webhooks/whatsapp
    ports:
      - "3025:3025"
    volumes:
      - baileys_sessions:/app/sessions
      - baileys_logs:/app/logs
    depends_on:
      - redis
    networks:
      - darwinai
    command: >
      sh -c "
        bun scripts/manage-api-keys.ts create user ${BAILEYS_API_KEY} &&
        bun start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3025/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: baileys-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - baileys_redis_data:/data
    networks:
      - darwinai
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  baileys_sessions:
    driver: local
  baileys_logs:
    driver: local
  baileys_redis_data:
    driver: local

networks:
  darwinai:
    external: true 